#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

lint_staged_files() {
  local dir="$1"
  local files=$(git diff --staged --name-only -- "$dir" | grep -E '\.jsx?$|\.tsx?$')
  
  if [ -n "$files" ]; then
    cd "$dir"
    npm run lint
    cd ..
  fi
}

lint_staged_files "client"
lint_staged_files "server"
