#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --name-only | grep --quiet "^client"
then
  cd client
  npm run lint
  cd ..
fi

if git diff --cached --name-only | grep --quiet "^server"
then
  cd server
  npm run lint
  cd ..
fi